//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ATOCTRL.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ATOCTRL_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDC_EDITRX                      1000
#define IDC_RICHEDITRX                  1001
#define IDC_COMBOCOMPORTNUMBER          1002
#define IDC_BUTTONCOM                   1003
#define IDC_RICHEDITTX                  1004
#define IDC_SLIDERMCLEVAL               1007
#define IDC_CHECKSLOPESTART             1008
#define IDC_CHECKHIGHACC                1009
#define IDC_CHECKGUARD                  1010
#define IDC_CHECKLEFTSELECT             1011
#define IDC_CHECKLEFTOPEN               1012
#define IDC_CHECKRIGHTSELECT            1013
#define IDC_CHECKRIGHTOPEN              1014
#define IDC_CHECKATOAUTORETURN          1015
#define IDC_CHECKATOMODE                1016
#define IDC_CHECKRETURNLEDNOLIGHT       1017
#define IDC_CHECKRETURNGLINT            1018
#define IDC_CHECKRETURNLIGHT            1019
#define IDC_CHECKATOSTARTLEDNOLIGHT     1020
#define IDC_CHECKATOSTARTGLINT          1021
#define IDC_CHECKATOSTARTLIGHT          1022
#define IDC_CHECKMAMODELEDNOLIGHT       1023
#define IDC_CHECKMAMODEGLINT            1024
#define IDC_CHECKMAMODELIGHT            1025
#define IDC_CHECKATOFAULTLEDNOLIGHT     1026
#define IDC_CHECKATOFAULTGLINT          1027
#define IDC_CHECKATOFAULTLIGHT          1028
#define IDC_CHECKZEROMODE               1029
#define IDC_CHECKRMMODE                 1030
#define IDC_CHECKCMMODE                 1031
#define IDC_CHECKNOMODE                 1032
#define IDC_EDITRETURNMCOUT             1033
#define IDC_CHECKRETURNSLOPESTART       1034
#define IDC_CHECKRETURNHIGHACC          1035
#define IDC_CHECKRETURNGUARD            1036
#define IDC_CHECKRETURNLEFTSELECT       1037
#define IDC_CHECKRETURNLEFTOPEN         1038
#define IDC_CHECKRETURNRIGHTSELECT      1039
#define IDC_CHECKRETURNRIGHTOPEN        1040
#define IDC_CHECKRETURNATOAUTORETURN    1041
#define IDC_CHECKRETURNATOMODERALAYENABLE 1042
#define IDC_EDITRETURNATOAUTORETURNLED  1043
#define IDC_EDITRETURNATOSTART          1044
#define IDC_EDITRETURNMAMODELED         1045
#define IDC_EDITRETURNATOFAULTLED       1046
#define IDC_EDITRETURNATPMODEOUT        1047
#define IDC_EDITRETURNMC                1048
#define IDC_EDITRETURNATOMODEEFFECT     1049
#define IDC_EDITRETURNATOMODESTATUS     1050
#define IDC_EDITRETURNATOAUTORETURNEFFECT 1051
#define IDC_EDITRETURNATOAUTORETURNSTATUS 1052
#define IDC_RETURNCANCELAUTORETURNSTATUS 1053
#define IDC_RETURNATOSTARTSTATUS        1054
#define IDC_RETURNMAMODESTATUS          1055
#define IDC_RETURNMCATOFACEUNIT         1056
#define IDC_BUTTONSEND                  1057
#define IDC_CHECKRETURNSLOPESTARTRE     1058
#define IDC_CHECKRETURNHIGHACCRE        1059
#define IDC_CHECKRETURNGUARDRE          1060
#define IDC_CHECKRETURNLEFTSELECTRE     1061
#define IDC_CHECKRETURNLEFTOPENRE       1062
#define IDC_CHECKRETURNRIGHTSELECTRE    1063
#define IDC_CHECKRETURNRIGHTOPENRE      1064
#define IDC_BUTTONONTIMESEND            1065

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1066
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
